language: ruby

rvm:
- 2.0.0
- 2.1.0
- 2.2.0
#- jruby-19mode # JRuby in 1.9 mode

env:
- DB=mysql
#- DB=pgsql
#- DB=sqlite

gemfile:
- Gemfile

cache:
  directories: vendor/bundle

# masterとdevelopブランチのみ実行対象に入れる
branches:
  only: 
    - master
    - develop

before_install:
- gem update --system
- gem --version
- sh -c "echo 'hello'"

before_script:
- gem update --system
- gem --version
- chmod -R 664 Gemfile
- cp ./README.md ./readme.txt


script:
- rake test

notifications:
  emails:
    - krakenbeal@gmail.com
#   - foo@example.com
  on_success: always # default: change
  on_failure: always

